### ISSUE TITLE
Issue with Rebilly\Sdk\Model\SubscriptionOrderEmbedded::setWebsite() - expects object, array given

### ISSUE THREAD

**Issue by Anemoiaa** [Rebilly/rebilly-php#666]
Hello there

I'm currently work with Subscriptions, and when making a call to getAllPaginator with the 'expand' parameter set to 'website', I encounter the following error:

`**Rebilly\Sdk\Model\SubscriptionOrderEmbedded::setWebsite(): Argument #1 ($website) must be of type ?object, array given, called in /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrderEmbedded.php on line 34**`

**Stacktrace:**
```
[2024-02-02 10:29:47] local.ERROR: Rebilly\Sdk\Model\SubscriptionOrderEmbedded::setWebsite(): Argument #1 ($website) must be of type ?object, array given, called in /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrderEmbedded.php on line 34 {"userId":1,"exception":"[object] (TypeError(code: 0): Rebilly\\Sdk\\Model\\SubscriptionOrderEmbedded::setWebsite(): Argument #1 ($website) must be of type ?object, array given, called in /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrderEmbedded.php on line 34 at /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrderEmbedded.php:96)
[stacktrace]
#0 /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrderEmbedded.php(34): Rebilly\\Sdk\\Model\\SubscriptionOrderEmbedded->setWebsite()
#1 /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrderEmbedded.php(52): Rebilly\\Sdk\\Model\\SubscriptionOrderEmbedded->__construct()
#2 /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrder.php(730): Rebilly\\Sdk\\Model\\SubscriptionOrderEmbedded::from()
#3 /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrder.php(240): Rebilly\\Sdk\\Model\\SubscriptionOrder->setEmbedded()
#4 /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionOrder.php(246): Rebilly\\Sdk\\Model\\SubscriptionOrder->__construct()
#5 /www/backend/vendor/rebilly/client-php/src/Model/SubscriptionFactory.php(24): Rebilly\\Sdk\\Model\\SubscriptionOrder::from()
#6 /www/backend/vendor/rebilly/client-php/src/Api/SubscriptionsApi.php(193): Rebilly\\Sdk\\Model\\SubscriptionFactory::from()
#7 [internal function]: Rebilly\\Sdk\\Api\\SubscriptionsApi->Rebilly\\Sdk\\Api\\{closure}()
#8 /www/backend/vendor/rebilly/client-php/src/Api/SubscriptionsApi.php(193): array_map()
#9 /www/backend/vendor/rebilly/client-php/src/Api/SubscriptionsApi.php(208): Rebilly\\Sdk\\Api\\SubscriptionsApi->getAll()
#10 /www/backend/vendor/rebilly/client-php/src/Paginator.php(122): Rebilly\\Sdk\\Api\\SubscriptionsApi->Rebilly\\Sdk\\Api\\{closure}()
#11 /www/backend/vendor/rebilly/client-php/src/Paginator.php(59): Rebilly\\Sdk\\Paginator->load()
#12 /www/backend/app/Repositories/SubscriptionRepository.php(77): Rebilly\\Sdk\\Paginator->current()
#13 /www/backend/app/Http/Controllers/CustomerController.php(55): App\\Repositories\\SubscriptionRepository->findByCustomerId()
```

**Snippet:**
```
$subscriptionsPaginator = $this->coreService->subscriptions()->getAllPaginator(
            filter: Rebilly::buildFilterString(['customerId' => $ids]),
            expand: 'website'
        );
```
It seems that the SDK is unable to parse the object as expected. The issue might be related to the structure of the returned data. Could you please investigate this issue and provide guidance on how to resolve it?

_This issue is not limited to the Subscription model; similar problems are observed with other models like Transactions._

SDK Version: 3.0.0
ENV: PHP 8.2

**Comment by ashkarpetin** [comment]
Hello, rebilly-php is autogenerated from Rebilly API docs. Right now it is unable to properly autogenerate code from `_embedded`. We are looking into the issue, but don't have exact ETA. Thanks for bringing attention to the issue.

**Comment by justnero** [comment]
Hi @Anemoiaa! Thank you for raising this issue.

All embedded models are now supported, check version [3.1.0](https://github.com/Rebilly/rebilly-php/releases/tag/3.1.0).
